// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bot.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

// Response is the response for each request to a Bot
type BotResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Body                 []byte   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	ContentType          string   `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BotResponse) Reset()         { *m = BotResponse{} }
func (m *BotResponse) String() string { return proto.CompactTextString(m) }
func (*BotResponse) ProtoMessage()    {}
func (*BotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{1}
}

func (m *BotResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BotResponse.Unmarshal(m, b)
}
func (m *BotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BotResponse.Marshal(b, m, deterministic)
}
func (m *BotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BotResponse.Merge(m, src)
}
func (m *BotResponse) XXX_Size() int {
	return xxx_messageInfo_BotResponse.Size(m)
}
func (m *BotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BotResponse proto.InternalMessageInfo

func (m *BotResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *BotResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *BotResponse) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

type APIRequest struct {
	BotStoreServer       uint32   `protobuf:"varint,1,opt,name=bot_store_server,json=botStoreServer,proto3" json:"bot_store_server,omitempty"`
	IpfsHandlerServer    uint32   `protobuf:"varint,2,opt,name=ipfs_handler_server,json=ipfsHandlerServer,proto3" json:"ipfs_handler_server,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIRequest) Reset()         { *m = APIRequest{} }
func (m *APIRequest) String() string { return proto.CompactTextString(m) }
func (*APIRequest) ProtoMessage()    {}
func (*APIRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{2}
}

func (m *APIRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIRequest.Unmarshal(m, b)
}
func (m *APIRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIRequest.Marshal(b, m, deterministic)
}
func (m *APIRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIRequest.Merge(m, src)
}
func (m *APIRequest) XXX_Size() int {
	return xxx_messageInfo_APIRequest.Size(m)
}
func (m *APIRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_APIRequest.DiscardUnknown(m)
}

var xxx_messageInfo_APIRequest proto.InternalMessageInfo

func (m *APIRequest) GetBotStoreServer() uint32 {
	if m != nil {
		return m.BotStoreServer
	}
	return 0
}

func (m *APIRequest) GetIpfsHandlerServer() uint32 {
	if m != nil {
		return m.IpfsHandlerServer
	}
	return 0
}

func (m *APIRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Success struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Success) Reset()         { *m = Success{} }
func (m *Success) String() string { return proto.CompactTextString(m) }
func (*Success) ProtoMessage()    {}
func (*Success) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{3}
}

func (m *Success) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Success.Unmarshal(m, b)
}
func (m *Success) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Success.Marshal(b, m, deterministic)
}
func (m *Success) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Success.Merge(m, src)
}
func (m *Success) XXX_Size() int {
	return xxx_messageInfo_Success.Size(m)
}
func (m *Success) XXX_DiscardUnknown() {
	xxx_messageInfo_Success.DiscardUnknown(m)
}

var xxx_messageInfo_Success proto.InternalMessageInfo

func (m *Success) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ByteData struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByteData) Reset()         { *m = ByteData{} }
func (m *ByteData) String() string { return proto.CompactTextString(m) }
func (*ByteData) ProtoMessage()    {}
func (*ByteData) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{4}
}

func (m *ByteData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByteData.Unmarshal(m, b)
}
func (m *ByteData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByteData.Marshal(b, m, deterministic)
}
func (m *ByteData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByteData.Merge(m, src)
}
func (m *ByteData) XXX_Size() int {
	return xxx_messageInfo_ByteData.Size(m)
}
func (m *ByteData) XXX_DiscardUnknown() {
	xxx_messageInfo_ByteData.DiscardUnknown(m)
}

var xxx_messageInfo_ByteData proto.InternalMessageInfo

func (m *ByteData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SetByKey struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetByKey) Reset()         { *m = SetByKey{} }
func (m *SetByKey) String() string { return proto.CompactTextString(m) }
func (*SetByKey) ProtoMessage()    {}
func (*SetByKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{5}
}

func (m *SetByKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetByKey.Unmarshal(m, b)
}
func (m *SetByKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetByKey.Marshal(b, m, deterministic)
}
func (m *SetByKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetByKey.Merge(m, src)
}
func (m *SetByKey) XXX_Size() int {
	return xxx_messageInfo_SetByKey.Size(m)
}
func (m *SetByKey) XXX_DiscardUnknown() {
	xxx_messageInfo_SetByKey.DiscardUnknown(m)
}

var xxx_messageInfo_SetByKey proto.InternalMessageInfo

func (m *SetByKey) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetByKey) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ByKey struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByKey) Reset()         { *m = ByKey{} }
func (m *ByKey) String() string { return proto.CompactTextString(m) }
func (*ByKey) ProtoMessage()    {}
func (*ByKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{6}
}

func (m *ByKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByKey.Unmarshal(m, b)
}
func (m *ByKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByKey.Marshal(b, m, deterministic)
}
func (m *ByKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByKey.Merge(m, src)
}
func (m *ByKey) XXX_Size() int {
	return xxx_messageInfo_ByKey.Size(m)
}
func (m *ByKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ByKey.DiscardUnknown(m)
}

var xxx_messageInfo_ByKey proto.InternalMessageInfo

func (m *ByKey) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetData struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetData) Reset()         { *m = GetData{} }
func (m *GetData) String() string { return proto.CompactTextString(m) }
func (*GetData) ProtoMessage()    {}
func (*GetData) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{7}
}

func (m *GetData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetData.Unmarshal(m, b)
}
func (m *GetData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetData.Marshal(b, m, deterministic)
}
func (m *GetData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetData.Merge(m, src)
}
func (m *GetData) XXX_Size() int {
	return xxx_messageInfo_GetData.Size(m)
}
func (m *GetData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetData.DiscardUnknown(m)
}

var xxx_messageInfo_GetData proto.InternalMessageInfo

func (m *GetData) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *GetData) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*BotResponse)(nil), "pb.BotResponse")
	proto.RegisterType((*APIRequest)(nil), "pb.APIRequest")
	proto.RegisterType((*Success)(nil), "pb.Success")
	proto.RegisterType((*ByteData)(nil), "pb.ByteData")
	proto.RegisterType((*SetByKey)(nil), "pb.SetByKey")
	proto.RegisterType((*ByKey)(nil), "pb.ByKey")
	proto.RegisterType((*GetData)(nil), "pb.GetData")
}

func init() { proto.RegisterFile("bot.proto", fileDescriptor_51d7d70385167023) }

var fileDescriptor_51d7d70385167023 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcf, 0x8e, 0x94, 0x40,
	0x10, 0xc6, 0x03, 0xf3, 0x97, 0x02, 0xd7, 0xb5, 0x4d, 0x0c, 0xce, 0x61, 0x83, 0x98, 0x28, 0x5e,
	0x58, 0x33, 0x3e, 0x81, 0x64, 0xcd, 0xba, 0xf1, 0x32, 0x69, 0x3c, 0x9a, 0x10, 0x60, 0xca, 0xec,
	0xc6, 0x95, 0x6e, 0xe9, 0xc2, 0xa4, 0x7d, 0x2a, 0x1f, 0xd1, 0xd0, 0x34, 0x2c, 0x1e, 0x8c, 0x73,
	0xfb, 0xaa, 0xea, 0x57, 0xf5, 0xd5, 0x54, 0x0f, 0xe0, 0x55, 0x82, 0x52, 0xd9, 0x0a, 0x12, 0xcc,
	0x95, 0x55, 0xbc, 0x81, 0xd5, 0x87, 0xef, 0x92, 0x74, 0xfc, 0x05, 0xfc, 0x4c, 0x10, 0x47, 0x25,
	0x45, 0xa3, 0x90, 0x3d, 0x83, 0xb5, 0xa2, 0x92, 0x3a, 0x15, 0x3a, 0x91, 0x93, 0xac, 0xb8, 0x8d,
	0x18, 0x83, 0x65, 0x25, 0x8e, 0x3a, 0x74, 0x23, 0x27, 0x09, 0xb8, 0xd1, 0xec, 0x05, 0x04, 0xb5,
	0x68, 0x08, 0x1b, 0x2a, 0x48, 0x4b, 0x0c, 0x17, 0x91, 0x93, 0x78, 0xdc, 0xb7, 0xb9, 0xcf, 0x5a,
	0x62, 0xfc, 0x0b, 0xe0, 0xfd, 0xe1, 0x86, 0xe3, 0x8f, 0x0e, 0x15, 0xb1, 0x04, 0xce, 0x2b, 0x41,
	0x85, 0x22, 0xd1, 0x62, 0xa1, 0xb0, 0xfd, 0x89, 0xad, 0xb1, 0x79, 0xc4, 0xcf, 0x2a, 0x41, 0x79,
	0x9f, 0xce, 0x4d, 0x96, 0xa5, 0xf0, 0xf4, 0x4e, 0x7e, 0x55, 0xc5, 0x6d, 0xd9, 0x1c, 0xef, 0xb1,
	0x1d, 0x61, 0xd7, 0xc0, 0x4f, 0xfa, 0xd2, 0xc7, 0xa1, 0x62, 0x79, 0x06, 0xcb, 0x63, 0x49, 0xa5,
	0x59, 0x21, 0xe0, 0x46, 0xc7, 0x2f, 0x61, 0x93, 0x77, 0x75, 0x8d, 0x4a, 0xb1, 0x10, 0x36, 0x6a,
	0x90, 0xc6, 0x6f, 0xcb, 0xc7, 0x30, 0xbe, 0x80, 0x6d, 0xa6, 0x09, 0xaf, 0x4a, 0x2a, 0xa7, 0x21,
	0xce, 0x6c, 0xc8, 0x5b, 0xd8, 0xe6, 0x48, 0x99, 0xfe, 0x84, 0x9a, 0x9d, 0xc3, 0xe2, 0x1b, 0x6a,
	0x53, 0xf6, 0x78, 0x2f, 0xa7, 0x0e, 0x77, 0xd6, 0xf1, 0x1c, 0x56, 0xff, 0xc0, 0xe3, 0x4b, 0xd8,
	0x5c, 0x23, 0x8d, 0x5e, 0xb2, 0xa4, 0x5b, 0x5b, 0x35, 0x7a, 0x6c, 0x70, 0xa7, 0x86, 0x7d, 0x03,
	0xdb, 0xcc, 0x1e, 0x86, 0x5d, 0xc0, 0xe2, 0x1a, 0x89, 0x79, 0xa9, 0xac, 0x52, 0x63, 0xb0, 0x0b,
	0x06, 0x69, 0xb7, 0x8f, 0x60, 0x91, 0x23, 0x31, 0x93, 0x1c, 0x57, 0xde, 0xf9, 0x26, 0xb2, 0x57,
	0x88, 0x60, 0x7d, 0x85, 0xf7, 0x48, 0x38, 0x1f, 0x32, 0x27, 0xf6, 0x97, 0xe0, 0xdf, 0x3c, 0xdc,
	0xb6, 0x1f, 0xd9, 0x5b, 0x1a, 0xc4, 0x2e, 0xfe, 0xb7, 0xe9, 0xfe, 0xb7, 0x03, 0x90, 0x09, 0xea,
	0x9f, 0xe7, 0xae, 0x46, 0xf6, 0x1a, 0x96, 0x07, 0xa1, 0x88, 0x9d, 0xf5, 0xd0, 0xc3, 0xc3, 0xef,
	0x1e, 0x9b, 0xa6, 0xd9, 0xdf, 0xec, 0xd5, 0x30, 0xf9, 0x14, 0xee, 0xd0, 0x9d, 0xc0, 0xbd, 0x99,
	0x7e, 0xda, 0xff, 0xd0, 0x6a, 0x6d, 0x3e, 0x82, 0x77, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc0,
	0x0c, 0x22, 0x1d, 0x11, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BotStoreClient is the client API for BotStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BotStoreClient interface {
	// TODO: stored data []byte might be better as json or json string objects?
	Get(ctx context.Context, in *ByKey, opts ...grpc.CallOption) (*ByteData, error)
	Set(ctx context.Context, in *SetByKey, opts ...grpc.CallOption) (*Success, error)
	Delete(ctx context.Context, in *ByKey, opts ...grpc.CallOption) (*Success, error)
}

type botStoreClient struct {
	cc *grpc.ClientConn
}

func NewBotStoreClient(cc *grpc.ClientConn) BotStoreClient {
	return &botStoreClient{cc}
}

func (c *botStoreClient) Get(ctx context.Context, in *ByKey, opts ...grpc.CallOption) (*ByteData, error) {
	out := new(ByteData)
	err := c.cc.Invoke(ctx, "/pb.BotStore/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botStoreClient) Set(ctx context.Context, in *SetByKey, opts ...grpc.CallOption) (*Success, error) {
	out := new(Success)
	err := c.cc.Invoke(ctx, "/pb.BotStore/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botStoreClient) Delete(ctx context.Context, in *ByKey, opts ...grpc.CallOption) (*Success, error) {
	out := new(Success)
	err := c.cc.Invoke(ctx, "/pb.BotStore/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BotStoreServer is the server API for BotStore service.
type BotStoreServer interface {
	// TODO: stored data []byte might be better as json or json string objects?
	Get(context.Context, *ByKey) (*ByteData, error)
	Set(context.Context, *SetByKey) (*Success, error)
	Delete(context.Context, *ByKey) (*Success, error)
}

// UnimplementedBotStoreServer can be embedded to have forward compatible implementations.
type UnimplementedBotStoreServer struct {
}

func (*UnimplementedBotStoreServer) Get(ctx context.Context, req *ByKey) (*ByteData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedBotStoreServer) Set(ctx context.Context, req *SetByKey) (*Success, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (*UnimplementedBotStoreServer) Delete(ctx context.Context, req *ByKey) (*Success, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterBotStoreServer(s *grpc.Server, srv BotStoreServer) {
	s.RegisterService(&_BotStore_serviceDesc, srv)
}

func _BotStore_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ByKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotStoreServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BotStore/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotStoreServer).Get(ctx, req.(*ByKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotStore_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetByKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotStoreServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BotStore/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotStoreServer).Set(ctx, req.(*SetByKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotStore_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ByKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotStoreServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BotStore/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotStoreServer).Delete(ctx, req.(*ByKey))
	}
	return interceptor(ctx, in, info, handler)
}

var _BotStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BotStore",
	HandlerType: (*BotStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _BotStore_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _BotStore_Set_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BotStore_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bot.proto",
}

// IpfsHandlerClient is the client API for IpfsHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IpfsHandlerClient interface {
	Get(ctx context.Context, in *GetData, opts ...grpc.CallOption) (*ByteData, error)
}

type ipfsHandlerClient struct {
	cc *grpc.ClientConn
}

func NewIpfsHandlerClient(cc *grpc.ClientConn) IpfsHandlerClient {
	return &ipfsHandlerClient{cc}
}

func (c *ipfsHandlerClient) Get(ctx context.Context, in *GetData, opts ...grpc.CallOption) (*ByteData, error) {
	out := new(ByteData)
	err := c.cc.Invoke(ctx, "/pb.IpfsHandler/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IpfsHandlerServer is the server API for IpfsHandler service.
type IpfsHandlerServer interface {
	Get(context.Context, *GetData) (*ByteData, error)
}

// UnimplementedIpfsHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedIpfsHandlerServer struct {
}

func (*UnimplementedIpfsHandlerServer) Get(ctx context.Context, req *GetData) (*ByteData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterIpfsHandlerServer(s *grpc.Server, srv IpfsHandlerServer) {
	s.RegisterService(&_IpfsHandler_serviceDesc, srv)
}

func _IpfsHandler_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpfsHandlerServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.IpfsHandler/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpfsHandlerServer).Get(ctx, req.(*GetData))
	}
	return interceptor(ctx, in, info, handler)
}

var _IpfsHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.IpfsHandler",
	HandlerType: (*IpfsHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _IpfsHandler_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bot.proto",
}

// BotserviceClient is the client API for Botservice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BotserviceClient interface {
	Post(ctx context.Context, in *APIRequest, opts ...grpc.CallOption) (*BotResponse, error)
	Get(ctx context.Context, in *APIRequest, opts ...grpc.CallOption) (*BotResponse, error)
	Put(ctx context.Context, in *APIRequest, opts ...grpc.CallOption) (*BotResponse, error)
	Delete(ctx context.Context, in *APIRequest, opts ...grpc.CallOption) (*BotResponse, error)
}

type botserviceClient struct {
	cc *grpc.ClientConn
}

func NewBotserviceClient(cc *grpc.ClientConn) BotserviceClient {
	return &botserviceClient{cc}
}

func (c *botserviceClient) Post(ctx context.Context, in *APIRequest, opts ...grpc.CallOption) (*BotResponse, error) {
	out := new(BotResponse)
	err := c.cc.Invoke(ctx, "/pb.Botservice/Post", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botserviceClient) Get(ctx context.Context, in *APIRequest, opts ...grpc.CallOption) (*BotResponse, error) {
	out := new(BotResponse)
	err := c.cc.Invoke(ctx, "/pb.Botservice/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botserviceClient) Put(ctx context.Context, in *APIRequest, opts ...grpc.CallOption) (*BotResponse, error) {
	out := new(BotResponse)
	err := c.cc.Invoke(ctx, "/pb.Botservice/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botserviceClient) Delete(ctx context.Context, in *APIRequest, opts ...grpc.CallOption) (*BotResponse, error) {
	out := new(BotResponse)
	err := c.cc.Invoke(ctx, "/pb.Botservice/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BotserviceServer is the server API for Botservice service.
type BotserviceServer interface {
	Post(context.Context, *APIRequest) (*BotResponse, error)
	Get(context.Context, *APIRequest) (*BotResponse, error)
	Put(context.Context, *APIRequest) (*BotResponse, error)
	Delete(context.Context, *APIRequest) (*BotResponse, error)
}

// UnimplementedBotserviceServer can be embedded to have forward compatible implementations.
type UnimplementedBotserviceServer struct {
}

func (*UnimplementedBotserviceServer) Post(ctx context.Context, req *APIRequest) (*BotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Post not implemented")
}
func (*UnimplementedBotserviceServer) Get(ctx context.Context, req *APIRequest) (*BotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedBotserviceServer) Put(ctx context.Context, req *APIRequest) (*BotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (*UnimplementedBotserviceServer) Delete(ctx context.Context, req *APIRequest) (*BotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterBotserviceServer(s *grpc.Server, srv BotserviceServer) {
	s.RegisterService(&_Botservice_serviceDesc, srv)
}

func _Botservice_Post_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotserviceServer).Post(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Botservice/Post",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotserviceServer).Post(ctx, req.(*APIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Botservice_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotserviceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Botservice/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotserviceServer).Get(ctx, req.(*APIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Botservice_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotserviceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Botservice/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotserviceServer).Put(ctx, req.(*APIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Botservice_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotserviceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Botservice/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotserviceServer).Delete(ctx, req.(*APIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Botservice_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Botservice",
	HandlerType: (*BotserviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Post",
			Handler:    _Botservice_Post_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Botservice_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Botservice_Put_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Botservice_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bot.proto",
}
